### ISSUE TITLE
snmptt can't extract hostname / IP address from net-snmp-5.7.2

### ISSUE THREAD

**Issue by danci1973** [snmptt/snmptt#1]
snmptrapd from net-snmp-5.7.2 is passing the hostname as **UDP: [10.80.48.15]:162->[172.24.224.68]:162**, which snmptt (1.4.2) translated to hostname **UDP10.4.32.10640492-172.24.224.68162** - i.e. it just removed some characters...

The reason is that the regex for hostname expects the unmodified string (as shown above), but there is another regex before that remove (most) non alphanumeric characters - including square brackets, colons and '>' sign.

I fixed the 1.4.2 version by changing the first regex not to remove colons and square brackets, and the second regex not to expect the '>' sign:

```
--- snmptt.orig 2021-06-09 13:01:33.361003231 +0200
+++ snmptt.new  2021-06-09 14:22:51.783547952 +0200
@@ -3253,7 +3253,7 @@

   chomp($tempvar[0]=<$input>); # hostname
   push(@rawtrap, $tempvar[0]);
-  $tempvar[0]  =~ s/[^a-zA-Z0-9.\-_]//g;  # Remove most non alphanumeric characters
+  $tempvar[0]  =~ s/[^a-zA-Z0-9.\-_:\[\]]//g;  # Remove most non alphanumeric characters

   if ($tempvar[0] eq "") {
     if ($DEBUGGING >= 1) {
@@ -3278,7 +3278,7 @@
   # With DNS resolution disabled in snmptrapd, some systems pass the hostname as:
   # UDP: [x.x.x.x]:161->[y.y.y.y]
   # If this is detected, use x.x.x.x as the hostname.
-  if ($tempvar[0] =~ /\[(\d+\.\d+\.\d+\.\d+)\].*?->\[(\d+\.\d+\.\d+\.\d+)\]/) {
+  if ($tempvar[0] =~ /\[(\d+\.\d+\.\d+\.\d+)\].*?-\[(\d+\.\d+\.\d+\.\d+)\]/) {
     $tempvar[0] = $1;
   }
```

Looking at the 1.5beta2 files, similar changes will be required.

**Comment by AlexB7** [comment]
Thanks for the bug report and fix. This has been added to 1.5beta3.
