### ISSUE TITLE
[Feature request] Normalise case for DNS request results

### ISSUE THREAD

**Issue by JDA88** [snmptt/snmptt#10]
**Used version:** 1.5 in Windows

If `dns_enable` option is on, IP are resolved, which is great. Unfortunately, DNS results are sometime inconsistent (lower or upper case) depending on a number of factor.

It would be great to have a `dns_normalise_case` option

- 0 = Leave result unchanged _(same as today)_
- 1 = Convert the result to lower case
- 2 = Convert the result to upper case

**Comment by nistorj** [comment]
+1

**Comment by AlexB7** [comment]
This has been added.  Please test.

**Comment by JDA88** [comment]
It works wonderfully, thank you very much!
