### ISSUE TITLE
Move custom columns substitution messages to debugging log

### ISSUE THREAD

**Issue by JDA88** [snmptt/snmptt#12]
Is it possible to move the custom columns substitution messages to the debugging log? (`DEBUGGING=2` probalby as they are not very usefull except for debugging)

Examples below:
```
Performing substitution on custom column: %VALUE%
Done performing substitution on custom column: %VALUE%
```

**Comment by AlexB7** [comment]
I have moved these to debug level 1 which matches the others.

**Comment by JDA88** [comment]
Thanks for that!
