### ISSUE TITLE
Unexpected substitution on the trap message

### ISSUE THREAD

**Issue by dpeddi** [snmptt/snmptt#13]
Hello,

In the environment I manage sometime it happens that some traps have the $ character in the body. 
In this particular case I have a string like "TRAP$CHECK"

The parameter that come into PREEXEC command line become "TRAPpublicHECK"

So the $C get substituted by the community name. 
From what I can understand from the documentation, the $C should be replaced in the resulting string from the FORMAT parameter and not  on the trap message. 

Is an expected behaviour?

Thank you

**Comment by AlexB7** [comment]
What version are you using?

**Comment by dpeddi** [comment]
Hello, 

I'm using 1.4, I know is quite old however I give a quick look at current version and I think it shouldn't have changed this behaviour.

Regards

**Comment by AlexB7** [comment]
Hi.

1.4.2 or higher should fix your problem as it strips out meta characters from the incoming trap.

**Comment by AlexB7** [comment]
1.4.2 or higher should fix your problem as it strips out meta characters from the incoming trap.
