### ISSUE TITLE
Packaging and automating the installation

### ISSUE THREAD

**Issue by elico** [snmptt/snmptt#15]
Hey,

I noticed that for a very long time the RHEL based OS's doesn't have any RPMs for snmptt.
I would like to build one for the latest version of snmptt.
I last version of src.rpm and spec I have found was on Fedora 17 epel 7.
The only OS that supplied 1.5 packaged version is Debian sid according to:
[pkgs.org](https://pkgs.org/search/?q=snmptt)

[snmptt-1.4.2-1.el7.src.rpm](https://download.fedoraproject.org/pub/epel/7/SRPMS/Packages/s/snmptt-1.4.2-1.el7.src.rpm)

From the SPEC file it seems pretty simple to install snmptt.

I will try to give it a shot for 1.5.

**Comment by AlexB7** [comment]
Were you able to create a package for 1.5?

**Comment by elico** [comment]
@AlexB7 I have created a package of 1.5 for Oracle Linux 8 and you can use the SRPM to re-build for other distro such as RHEL while it should be compatible as it is.
The sources are at:
https://www.ngtech.co.il/repo/oracle/8/SRPMS/snmptt-1.5-1.el8.src.rpm

And the binary package is at:
https://www.ngtech.co.il/repo/oracle/8/x86_64/snmptt-1.5-1.el8.noarch.rpm

Works right out of the box as far as I can tell.
