### ISSUE TITLE
Error loop - Win32::ODBC error: Unable to perform INSERT

### ISSUE THREAD

**Issue by JDA88** [snmptt/snmptt#17]
My instances of "snmptt" are configured to write to a database (`sql_win32_odbc_*` options) and everything works fine.
But after some time if (I suspect if there is a communication error of some sort) the logs spam the following messages and no further communication occurs until i restart the service
`Win32::ODBC error: Unable to perform INSERT INTO: [911] [1] "[Microsoft][ODBC SQL Server Driver]Communication link failure"`

I have deployed "snmptt" on 11 differents servers wordwide and the time it take to "fail" is variable (from a few hours to 4-5days) but it's very consistant.

How can i provide you more information / logs?
Is there a way to tell "snmptt" to retry after an error and not stay in a fail loop?
Is this something i have to configure on the ODBC connector?

**Comment by AlexB7** [comment]
I have updated the Win32::ODBC section to retry three times when there is a failure doing an INSERT.  It also attempts to reconnect to the database if "Communication link failure" is detect.

I have not tested this so can you please test and let me know if it works as expected?

**Comment by JDA88** [comment]
I'm deploying it to see if it fixes the issue, I'll come back to you "next year" :)

At the same time on my side I updated from the native `SQL Server` to the updated one `ODBC Driver 18 for SQL Server` wich also have some retry mecanics embeded.

**Comment by JDA88** [comment]
Withe the new driver the error is different, but the problem persist even with the retry you implemented

This one first:
`Win32::ODBC error: Unable to perform INSERT INTO: [10054] [1] "[Microsoft][ODBC Driver 18 for SQL Server]TCP Provider: An existing connection was forcibly closed by the remote host.`

Then spaming this one on every try:
`Win32::ODBC error: Unable to perform INSERT INTO: [911] [1] "[Microsoft][ODBC Driver 18 for SQL Server]The connection is broken and recovery is not possible. The connection is marked by the client driver as unrecoverable. No attempt was made to restore the connection."`

Restarting the process fixes the issue.

I can see three options:
- Find why snmptt ODBC componant is stuck on a bad state once an issue occurs. Maybe reset the object and instance a new one?
- Try to keep the retry logic and add 2 config parameters: Retry count & Retry delay + some log output to help debug
- Have the script Exit on DB communication error, then an external process can restart it

This is the main problem for me snmptt is stuck on a fail loop and I have no way to detect it unless i look at the logs or check the last contact DateTime on the DB

**Comment by AlexB7** [comment]
I changed it so that it attempts to reconnect for any error instead of looking for "Communication link failure".  Can you test again?

You should see "Attempting to re-open Win32::ODBC connection" in the debug log and Windows Event Log.

**Comment by JDA88** [comment]
Thank you. I'm deploying this version, I'll let you know the result in a week

**Comment by JDA88** [comment]
It looks like theis version is much stable on the SQL connexion side.
I think we can close the issue. Thank you very much!

**Comment by AlexB7** [comment]
Is SNMPTT reconnecting when the connection drops or are you saying your new ODBC client is no longer dropping the connection?  There will be log entries for the reconnection.

**Comment by JDA88** [comment]
> Is SNMPTT reconnecting when the connection drops or are you saying your new ODBC client is no longer dropping the connection? There will be log entries for the reconnection.

Good question, those logs are only visible if `DEBUGGING >= 1 ` correct? If yes then I dont have the information as the config file was reseted with the lst release. I have set it back to 1 and I will come back to you when i get the answer

**Comment by JDA88** [comment]
I can find a few of those in the logs:

```
Win32::ODBC error: Unable to perform INSERT INTO: [10054] [1] "[Microsoft][ODBC Driver 18 for SQL Server]TCP Provider: An existing connection was forcibly closed by the remote host.
"
Attempting to re-open Win32::ODBC connection
```

So the re-open logic is working as intended ; Thank you again!
