### ISSUE TITLE
integers are not correctly translated when net_snmp_perl_cache_enable is set to 1

### ISSUE THREAD

**Issue by nx-sbourdeaud** [snmptt/snmptt#18]
When the net_snmp_perl_cache_enable setting is set to 1 in /etc/snmp/snmptt.ini and translate_integers is also set to 1, translation is only correct the first time.  Any subsequent translation uses the previous translated value regardless of the integer value.

For example, in the Nutanix MIB, traps use the 4th variable to determine the severity based on an integer value between 1 and 4.  When the first trap is received, the variable integer is correctly translated to say warning (assuming the integer value was 2).  The next traps will always be translated to warning even if the integer value is not 2.

When you disable the cache, the translation is always correctly done.
This has been tested with snmptt 1.5 and the latest Perl-Net-Snmp release available in EPEL for CentOS/RHEL 7 (net-snmp-perl-5.7.2-49.el7_9.2.x86_64).

**Comment by AlexB7** [comment]
This has been fixed for 1.5.1.
