### ISSUE TITLE
unknown_trap_preexec option in snmptt.ini is missing

### ISSUE THREAD

**Issue by Ashark** [snmptt/snmptt#3]
Currently snmptt v1.4 in /etc/snmp/snmptt.ini allows you to use the options unknown_trap_exec and unknown_trap_exec_format. But there is no unknown_trap_preexec option.

In my case, for all traps that I convert, I use a preexec line. It determines if the sender ip address can be resolved to the host name, and in case it cannot, returns the "undefined_host". Then I replace host name ($r) to the result of preexec (i.e. to resolved host name or to undefined_host). Because if I do not do that, the snmptt sends $r as ip address, which is unexpected and unwanted. In that case the exec command I use (submit_check_result to nagios) is formed with ip address, which is not used as any host name in nagios, so it effectively drops the submitted information. But I created pseudo host "undefined_host" in nagios, and traps from unresolved hosts go to it.

Also, I use second preexec line to add the sender ip to the text of description. In case of normal host resolving, the text is not added (I removed if ($result eq '') { $result = "(no output from PREEXEC)\n"; } from /usr/bin/snmptt). 

So my converted events look like this in snmptt.conf:
```
EVENT stpxInconsistencyUpdate .1.3.6.1.4.1.9.9.82.2.0.1 "Status Events" Normal
FORMAT stpxInconsistencyUpdate - stpxInconsistentState:$1 
PREEXEC if /usr/bin/[ "$A" == "$aA" ]; then echo undefined_host; else echo $A; fi
PREEXEC if /usr/bin/[ "$A" == "$aA" ]; then echo " Unable to resolve host name (no ptr record) for address $aA, so this trap goes to undefined_host."; fi
EXEC /bin/bash /usr/local/bin/trap/submit_check_result $p1 stp 0 "stpxInconsistencyUpdate - stpxInconsistentState:$1 $p2"
```

Now, I also want to catch traps that are not in the configs. I want them to go to some host (known or undefined_host) for service "other_traps". This can be done with unknown_trap_exec and unknown_trap_exec_format. But no way to use preexec for them.

I suggest adding unknown_trap_preexec option to be available in snmptt.ini.
I also suggest that $r should not returned ip in any case. Probably, better create another variable that will behave like $r currently.

Currently, I have found two workarounds.
### Workaround 1. Create a separate script which will handle the wanted preexec function.

In my case the script is the following
```
#!/bin/bash

if [[ "$#" != 1 ]] ; then 
	echo Error, expected only one argument
	exit 1
fi

host_name=$(echo "$1" | cut -f 1 -d " ")  # $A
host_address=$(echo "$1" | cut -f 2 -d " ")  # $aA
trap_oid_name=$(echo "$1" | cut -f 3 -d " ")  # $O
trap_oid_number=$(echo "$1" | cut -f 4 -d " ")  #$o
variables_and_values=$(echo "$1" | cut -f 5- -d " ")  # $-*

# Determine if address was resolved to host name. If host name contains host address, then it was not resolved, so we replace it with undefined_host.
if /usr/bin/[ "$host_name" == "$host_address" ]; then
	TO_HOST="undefined_host";
	ADDITIONAL_TEXT="Unable to determine host name (missing ptr record) for address $host_address, so trap goes to undefined_host."
else
	TO_HOST="$host_name";
	ADDITIONAL_TEXT="" # Determined, no need to add any text.
fi

/bin/bash /usr/local/bin/trap/submit_check_result "$TO_HOST" other_traps 2 "Got trap $trap_oid_name ($trap_oid_number). It is not in snmptt.conf, so it goes to other_traps. $ADDITIONAL_TEXT The following variables and values were sent: $variables_and_values"
```
and used the following lines in snmptt.ini for invoking it:
```
unknown_trap_exec = /etc/snmp/other_traps_handler.sh
unknown_trap_exec_format = $A $aA $O $o $-*
```

### Workaround 2. Add the .* event to the end of snmptt.conf
Manually append the following to the end of config:
```
EVENT other_event .* "Some other event" Normal
FORMAT Got trap $O ($o).  It is not in snmptt.conf, so it goes to other_traps. The following variables and values were sent: $-*
PREEXEC if /usr/bin/[ "$A" == "$aA" ]; then echo undefined_host; else echo $A; fi
PREEXEC if /usr/bin/[ "$A" == "$aA" ]; then echo " Unable to determine host name (missing ptr record) for address $aA, so trap goes to undefined_host."; fi
EXEC /bin/bash /usr/local/bin/trap/submit_check_result $p1 other_traps 2 "$Fz $p2"
```

**Comment by AlexB7** [comment]
I have added this feature for the snmptt_1.5beta3 release.  Please test and let me know if there are any issues.

snmptt.ini:

**Comment by Ashark** [comment]
Hello, AlexB7.
I currently removed unknown traps from my configs. But when I need that, I will test and report issues if any.
Thank you for implementation.

**Comment by AlexB7** [comment]
I have added this feature for the snmptt_1.5beta2 release.
