### ISSUE TITLE
snmpttconvertmib add --preexec option

### ISSUE THREAD

**Issue by Ashark** [snmptt/snmptt#4]
Currently (SNMPTTCONVERTMIB v1.4.2) you can use --exec option for converting mibs to specify the EXEC line. But there is no such thing for PREEXEC lines, the only way to add it is manually editing the converted config. Not a big deal, because you can use sed for this, like that
```
# 1st step
snmpttconvertmib --in="$mib_path" --out=snmptt.conf.cisco --exec='/bin/bash /usr/local/bin/trap/submit_check_result $p1 '"$Service $Status" -net_snmp_perl --format=4

# 2nd step
preexec1='PREEXEC if /usr/bin/[ "$A" == "$aA" ]; then echo undefined_host; else echo $A; fi'
preexec2='PREEXEC if /usr/bin/[ "$A" == "$aA" ]; then echo "The sender address is $aA"; fi'
sed -i '/^EXEC/i '"$preexec1"'' snmptt.conf.cisco # <-- insert the preexec1 line to the config
sed -i '/^EXEC/i '"$preexec2"'' snmptt.conf.cisco # <-- insert the preexec2 line to the config
sed -i '/^EXEC/ s/"$/$p2"/' snmptt.conf.cisco # <-- add preexec2 result to the end of exec text
```
But still, it would be convenient to specify PREEXEC line (or several lines) with --preexec option with snmpttconvertmib.

**Comment by AlexB7** [comment]
Thanks for the suggestion.  This has been added to 1.5beta3.
