### ISSUE TITLE
Traps are always logged into Application event log

### ISSUE THREAD

**Issue by JDA88** [snmptt/snmptt#7]
**Used version:** 1.5 in Windows

**Expected behavior:** `eventlog_enable` is at 0 so I expected the traps to not be logged into the Application event log
**Behavior:** I don’t seen any difference in trap login no matter the value of `eventlog_enable`

Am i missing something? The doc state : "_# Set to 1 to enable logging of *TRAPS* to the event log._"

PS: It will be fixed in 1.5.1

**Comment by AlexB7** [comment]
This has been fixed in 1.5.1.
