### ISSUE TITLE
[Feature request] Variable to switch dates to UNC in the database

### ISSUE THREAD

**Issue by JDA88** [snmptt/snmptt#8]
**Used version:** 1.5 in Windows

We have multiple instances of snmptt in multiple sites storing data in SQL and even though we found a way to get the correct date across multiple time zones, it would be easier to have snmptt store those date in UNC before sending then to the three supported tables (snmptt, snmptt_unknown and snmptt_statistics)

**Comment by AlexB7** [comment]
I have added snmptt.ini options date_time_utc and date_time_utc_sql for UTC support.  I have not tested with SQL.  Can you test and let me know if it's working?

**Comment by JDA88** [comment]
> I have added snmptt.ini options date_time_utc and date_time_utc_sql for UTC support. I have not tested with SQL. Can you test and let me know if it's working?

I'll let you know ASAP!

**Comment by JDA88** [comment]
When I start `snmptt` I immediately get the following line in the logs:
`Argument "" isn't numeric in numeric eq (==) at snmptt line 7093, <$fh_FILE> line 1.`
Wich trace back to code:
`if ($t_time == "") {`
No idea why but all the dates (logs and SQL are still in local time)

**Comment by JDA88** [comment]
Ok I found the root cause:
No matter the `$stat_time_format_sql` state (defined or not) the time will come from `get_time_sql()`
But with `$date_time_format_sql`, if it is not defined the time will come from `@localtime_array`. It will only come from `get_time_sql()` if it is undefined. 

But then the SQL injection fail because the format is invalid:
`Win32::ODBC error: Unable to perform INSERT INTO: [241] [1] "[Microsoft][ODBC SQL Server Driver][SQL Server]Conversion failed when converting date and/or time from character string."`

**Comment by AlexB7** [comment]
$t_time == "" should have been $t_time eq "".

This is fixed in git.  Can you pull down the latest and test again?

**Comment by JDA88** [comment]
> This is fixed in git. Can you pull down the latest and test again?

This fixes the error message bellow but not the fact that UNC date is only working on table stat
`Argument "" isn't numeric in numeric eq (==) at snmptt line 7093, <$fh_FILE> line 1.`

**Comment by AlexB7** [comment]
Can you test again with the latest code?  I believe I found the issue with date_time_format_sql.

For "SNMPTT 1.5 started: UTCDATE", I'll have to do some more testing as it works under Linux.  Similar code also works with Windows.

What version of Perl are you using and which package?  ActiveState, Strawberry..

**Comment by JDA88** [comment]
I have juste tested the new version. It fixes the issue, now the tree table have UTC dates. Thank you!
For Perl I'm using `strawberry-perl-5.32.1.1-64bit-portable`

About the behaviour with  `date_time_utc = 1` and `DEBUGGING = 1` I probably wasn't clear enough.
I get the following line in the logs:
`********** SNMPTT 1.5 started: Fri Aug 19 16:52:09 2022 **********` _(Local date)_
And i suspect I should get:
`********** SNMPTT 1.5 started: Fri Aug 19 14:52:09 2022 **********` _(UTC date)_

I personnaly don't care as i only need UTC date in the database anyway but I just wanted to point it out if it's unexpected

**Comment by AlexB7** [comment]
I tested with strawberry-perl-5.32.1.1 and I get the message in UTC when date_time_utc = 1.

********** SNMPTT 1.5 started: Sat Aug 20 01:13:17 2022 **********

I'll close this request for now.  If you still have an issue, let me know.
