### ISSUE TITLE
[Feature request] Add support to custom columns to the statistics table

### ISSUE THREAD

**Issue by JDA88** [snmptt/snmptt#9]
**Used version:** 1.5 in Windows

The custom columns feature is great and very useful; can you also add support to the statistics table?

**Comment by AlexB7** [comment]
If implemented, what would you be adding to the statistics table?

**Comment by JDA88** [comment]
> If implemented, what would you be adding to the statistics table?

Two things:

- The local time zone (used after to compute the UTC time)
- The “source” as we have multiple instance of snmptt and I don’t want to deal with one stat table per source

**Comment by AlexB7** [comment]
I have added this feature but I haven't tested it yet.  Are you able to test?  Try using $H.  Also try some other variables such as $C and $s to make they are empty.  sql_custom_columns_statistics in snmptt.ini.

**Comment by JDA88** [comment]
> Are you able to test? 
I'll test that tomorrow, thank you very much!

**Comment by JDA88** [comment]
I have tested the `sql_custom_columns_statistics` option, it work wonderfully. All the suggested variables work perfectly also (`$H` `$C` and `$s`)
Thank you very much!
